### ISSUE TITLE
Multiple permission

### ISSUE THREAD

**Issue by drchopper** [k0shk0sh/PermissionHelper#10]
Hallo,

I want showing my Permissions like this. But my code doesn't work. It only show always the first permission of the list. Could you help me pls.

![unbenannt](https://cloud.githubusercontent.com/assets/13781543/14075224/8486c396-f4d7-11e5-8fba-bb6f2fd64e2d.PNG)

```
public final static String WRITE_EXTERNAL_STORAGE_PERMISSION = Manifest.permission.WRITE_EXTERNAL_STORAGE;
public final static String ACCESS_FINE_LOCATION_PERMISSION = Manifest.permission.ACCESS_FINE_LOCATION;
public final static String CAMERA_PERMISSION = Manifest.permission.CAMERA;

public final static String[] MULTIPLE_PERMISSIONS = {WRITE_EXTERNAL_STORAGE_PERMISSION,
            ACCESS_FINE_LOCATION_PERMISSION,
            CAMERA_PERMISSION};
```

```
permissionHelper.setForceAccepting(false)
                .request(PermissionsStatesHelper.MULTIPLE_PERMISSIONS);
```

**Comment by k0shk0sh** [comment]
i'm working on the fix for this permission right now. will push an update
by today. thanks for being patience.

_Thanks._
_Best Regards,_
_Kosh_

https://about.me/imkosh?promo=email_sig

**Comment by k0shk0sh** [comment]
updated to v 1.0.9 please do update your dependency after awhile from this comment.

**Comment by vishnuchd** [comment]
This problem still exists in Android 6.0.1.
please help

**Comment by k0shk0sh** [comment]
Have you updated the library dependcy to latest? 1.09?

On Wednesday, 30 March 2016, Vishnu Sharma notifications@github.com wrote:

> This problem still exists in Android 6.0.1.
> please help
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/k0shk0sh/PermissionHelper/issues/10#issuecomment-203272638

## 

Thanks.
Best Regards, Kosh

**Comment by vishnuchd** [comment]
yes

**Comment by k0shk0sh** [comment]
Can you attach an example code of the issue? Because i cant trigger it

On Wednesday, 30 March 2016, Vishnu Sharma notifications@github.com wrote:

> yes
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/k0shk0sh/PermissionHelper/issues/10#issuecomment-203277300

## 

Thanks.
Best Regards, Kosh

**Comment by vishnuchd** [comment]
i used the code from 
public class Login extends AppCompatActivity implements OnPermissionCallback ,GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener, View.OnClickListener {

```
private boolean isSingle;
private AlertDialog builder,alertdialog;
private PermissionHelper permissionHelper;
private String[] neededPermission;
ProgressDialog pDialog;// = new ProgressDialog(this);


private final String[] MULTI_PERMISSIONS = new String[]{
        Manifest.permission.GET_ACCOUNTS,
        Manifest.permission.WRITE_EXTERNAL_STORAGE,
        Manifest.permission.CAMERA
};



private static final String TAG = "SignInActivity";
private static final int RC_SIGN_IN = 9001;
```

  //  private UiLifecycleHelper uiHelper;
    private GoogleApiClient mGoogleApiClient;
    private TextView mStatusTextView;
    private ProgressDialog mProgressDialog;
    private boolean mIntentInProgress;

```
static String regId = "";

AsyncTask<Void, Void, Void> mRegisterTask;
@Override
protected void onCreate(Bundle savedInstanceState) {

    super.onCreate(savedInstanceState);

    FacebookSdk.sdkInitialize(Login.this);
    setContentView(R.layout.activity_login);
    pDialog = new ProgressDialog(this);
    pDialog.setMessage("Loading...");






    permissionHelper = PermissionHelper.getInstance(this);
    permissionHelper
            .setForceAccepting(true) // default is false. its here so you know that it exists.
            .request(MULTI_PERMISSIONS);
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    pref = PreferenceManager.getDefaultSharedPreferences(Login.this);



// [START onActivityResult]
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    permissionHelper.onActivityForResult(requestCode);

    if (requestCode == RC_SIGN_IN) {
        if (resultCode != RESULT_OK)
        {
            mSignInClicked = false;
        }

        mIntentInProgress = false;

        if (!mGoogleApiClient.isConnecting())
        {
            mGoogleApiClient.connect();
        }
    }else
    {
        callbackManager.onActivityResult(requestCode, resultCode, data);
    //    uiHelper.onActivityResult(requestCode, resultCode, data);
    }
}
// [END onActivityResult]









@Override
public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    permissionHelper.onRequestPermissionsResult(requestCode, permissions, grantResults);
}

@Override
public void onPermissionGranted(String[] permissionName) {
    //   result.setText("Permission(s) " + Arrays.toString(permissionName) + " Granted");
    Log.i("onPermissionGranted", "Permission(s) " + Arrays.toString(permissionName) + " Granted");
}

@Override
public void onPermissionDeclined(String[] permissionName) {
    //  result.setText("Permission(s) " + Arrays.toString(permissionName) + " Declined");
    Log.i("onPermissionDeclined", "Permission(s) " + Arrays.toString(permissionName) + " Declined");
}

@Override
public void onPermissionPreGranted(String permissionsName) {
    //  result.setText("Permission( " + permissionsName + " ) preGranted");
    Log.i("onPermissionPreGranted", "Permission( " + permissionsName + " ) preGranted");
}

@Override
public void onPermissionNeedExplanation(String permissionName) {
   // Log.i("NeedExplanation", "Permission( " + permissionName + " ) needs Explanation");
    if (!isSingle) {
        neededPermission = PermissionHelper.declinedPermissions(this, MULTI_PERMISSIONS);
        StringBuilder builder = new StringBuilder(neededPermission.length);
        if (neededPermission.length > 0) {
            for (String permission : neededPermission) {
                builder.append(permission).append("\n");
            }
        }
        // result.setText("Permission( " + builder.toString() + " ) needs Explanation");
        AlertDialog alert = getAlertDialog(neededPermission, builder.toString());
        if (!alert.isShowing()) {
            alert.show();
        }
    } else {
        //   result.setText("Permission( " + permissionName + " ) needs Explanation");
        getAlertDialog(permissionName).show();
    }
}

public AlertDialog getAlertDialog(final String permission) {
    if (builder == null) {
        builder = new AlertDialog.Builder(this)
                .setTitle("Permission Needs Explanation").create();
    }
    builder.setButton(DialogInterface.BUTTON_POSITIVE, "Request", new DialogInterface.OnClickListener() {
        @Override
        public void onClick(DialogInterface dialog, int which) {
            permissionHelper.requestAfterExplanation(permission);
        }
    });
    builder.setMessage(" Please allow for the smooth function of App");
    return builder;
}
public AlertDialog checkinternet() {
    if (alertdialog == null) {
        alertdialog = new AlertDialog.Builder(this)
                .setTitle("Alert").create();
    }
    alertdialog.setButton(DialogInterface.BUTTON_POSITIVE, "Ok", new DialogInterface.OnClickListener() {
        @Override
        public void onClick(DialogInterface dialog, int which) {
            alertdialog.dismiss();
        }
    });
    alertdialog.setMessage("Please check your internet connection");

    return alertdialog;
}
@Override
public void onPermissionReallyDeclined(String permissionName) {
  //  AppController.getInstance().Showtoastlog("Permission " + permissionName + " can only be granted from SettingsScreen");
    Log.i("ReallyDeclined", "Permission " + permissionName + " can only be granted from settingsScreen");
    /** you can call  {@link PermissionHelper#openSettingsScreen(Context)} to open the settings screen */
}

@Override
public void onNoPermissionNeeded() {
    // result.setText("Permission(s) not needed");
    Log.i("onNoPermissionNeeded", "Permission(s) not needed");
}
public AlertDialog getAlertDialog(final String[] permissions, final String permissionName) {
    if (builder == null) {
        builder = new AlertDialog.Builder(this)
                .setTitle("Permission Needs Explanation").create();
    }
    builder.setButton(DialogInterface.BUTTON_POSITIVE, "Request", new DialogInterface.OnClickListener() {
        @Override
        public void onClick(DialogInterface dialog, int which) {
            permissionHelper.requestAfterExplanation(permissions);
        }
    });
    builder.setMessage(" Please allow for the smooth function of App");
    return builder;
}


@Override
protected void onResume() {
    super.onResume();

    // register GCM registration complete receiver
    LocalBroadcastManager.getInstance(this).registerReceiver(mRegistrationBroadcastReceiver,
            new IntentFilter(Config.REGISTRATION_COMPLETE));

    // register new push message receiver
    // by doing this, the activity will be notified each time a new message arrives
    LocalBroadcastManager.getInstance(this).registerReceiver(mRegistrationBroadcastReceiver,
            new IntentFilter(Config.PUSH_NOTIFICATION));
}

@Override
protected void onPause() {
    LocalBroadcastManager.getInstance(this).unregisterReceiver(mRegistrationBroadcastReceiver);
    super.onPause();
}
```

}

**Comment by k0shk0sh** [comment]
Okay thanks for the example, i will have a look at it and update you.

On Wednesday, 30 March 2016, Vishnu Sharma notifications@github.com wrote:

> i used the code from
> public class Login extends AppCompatActivity implements
> OnPermissionCallback ,GoogleApiClient.ConnectionCallbacks,
> GoogleApiClient.OnConnectionFailedListener, View.OnClickListener {
> 
> private boolean isSingle;
> private AlertDialog builder,alertdialog;
> private PermissionHelper permissionHelper;
> private String[] neededPermission;
> ProgressDialog pDialog;// = new ProgressDialog(this);
> 
> private final String[] MULTI_PERMISSIONS = new String[]{
>         Manifest.permission.GET_ACCOUNTS,
>         Manifest.permission.WRITE_EXTERNAL_STORAGE,
>         Manifest.permission.CAMERA
> };
> 
> private static final String TAG = "SignInActivity";
> private static final int RC_SIGN_IN = 9001;
> 
> // private UiLifecycleHelper uiHelper;
> private GoogleApiClient mGoogleApiClient;
> private TextView mStatusTextView;
> private ProgressDialog mProgressDialog;
> private boolean mIntentInProgress;
> 
> static String regId = "";
> 
> AsyncTask<Void, Void, Void> mRegisterTask;
> @Override
> protected void onCreate(Bundle savedInstanceState) {
> 
> ```
> super.onCreate(savedInstanceState);
> 
> FacebookSdk.sdkInitialize(Login.this);
> setContentView(R.layout.activity_login);
> pDialog = new ProgressDialog(this);
> pDialog.setMessage("Loading...");
> 
> 
> 
> 
> 
> 
> permissionHelper = PermissionHelper.getInstance(this);
> permissionHelper
>         .setForceAccepting(true) // default is false. its here so you know that it exists.
>         .request(MULTI_PERMISSIONS);
> Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
> pref = PreferenceManager.getDefaultSharedPreferences(Login.this);
> ```
> 
> // [START onActivityResult]
> @Override
> public void onActivityResult(int requestCode, int resultCode, Intent data) {
>     super.onActivityResult(requestCode, resultCode, data);
> 
> ```
> permissionHelper.onActivityForResult(requestCode);
> 
> if (requestCode == RC_SIGN_IN) {
>     if (resultCode != RESULT_OK)
>     {
>         mSignInClicked = false;
>     }
> 
>     mIntentInProgress = false;
> 
>     if (!mGoogleApiClient.isConnecting())
>     {
>         mGoogleApiClient.connect();
>     }
> }else
> {
>     callbackManager.onActivityResult(requestCode, resultCode, data);
> //    uiHelper.onActivityResult(requestCode, resultCode, data);
> }
> ```
> 
> }
> // [END onActivityResult]
> 
> @Override
> public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
>     permissionHelper.onRequestPermissionsResult(requestCode, permissions, grantResults);
> }
> 
> @Override
> public void onPermissionGranted(String[] permissionName) {
>     //   result.setText("Permission(s) " + Arrays.toString(permissionName) + " Granted");
>     Log.i("onPermissionGranted", "Permission(s) " + Arrays.toString(permissionName) + " Granted");
> }
> 
> @Override
> public void onPermissionDeclined(String[] permissionName) {
>     //  result.setText("Permission(s) " + Arrays.toString(permissionName) + " Declined");
>     Log.i("onPermissionDeclined", "Permission(s) " + Arrays.toString(permissionName) + " Declined");
> }
> 
> @Override
> public void onPermissionPreGranted(String permissionsName) {
>     //  result.setText("Permission( " + permissionsName + " ) preGranted");
>     Log.i("onPermissionPreGranted", "Permission( " + permissionsName + " ) preGranted");
> }
> 
> @Override
> public void onPermissionNeedExplanation(String permissionName) {
>    // Log.i("NeedExplanation", "Permission( " + permissionName + " ) needs Explanation");
>     if (!isSingle) {
>         neededPermission = PermissionHelper.declinedPermissions(this, MULTI_PERMISSIONS);
>         StringBuilder builder = new StringBuilder(neededPermission.length);
>         if (neededPermission.length > 0) {
>             for (String permission : neededPermission) {
>                 builder.append(permission).append("\n");
>             }
>         }
>         // result.setText("Permission( " + builder.toString() + " ) needs Explanation");
>         AlertDialog alert = getAlertDialog(neededPermission, builder.toString());
>         if (!alert.isShowing()) {
>             alert.show();
>         }
>     } else {
>         //   result.setText("Permission( " + permissionName + " ) needs Explanation");
>         getAlertDialog(permissionName).show();
>     }
> }
> 
> public AlertDialog getAlertDialog(final String permission) {
>     if (builder == null) {
>         builder = new AlertDialog.Builder(this)
>                 .setTitle("Permission Needs Explanation").create();
>     }
>     builder.setButton(DialogInterface.BUTTON_POSITIVE, "Request", new DialogInterface.OnClickListener() {
>         @Override
>         public void onClick(DialogInterface dialog, int which) {
>             permissionHelper.requestAfterExplanation(permission);
>         }
>     });
>     builder.setMessage(" Please allow for the smooth function of App");
>     return builder;
> }
> public AlertDialog checkinternet() {
>     if (alertdialog == null) {
>         alertdialog = new AlertDialog.Builder(this)
>                 .setTitle("Alert").create();
>     }
>     alertdialog.setButton(DialogInterface.BUTTON_POSITIVE, "Ok", new DialogInterface.OnClickListener() {
>         @Override
>         public void onClick(DialogInterface dialog, int which) {
>             alertdialog.dismiss();
>         }
>     });
>     alertdialog.setMessage("Please check your internet connection");
> 
> ```
> return alertdialog;
> ```
> 
> }
> @Override
> public void onPermissionReallyDeclined(String permissionName) {
>   //  AppController.getInstance().Showtoastlog("Permission " + permissionName + " can only be granted from SettingsScreen");
>     Log.i("ReallyDeclined", "Permission " + permissionName + " can only be granted from settingsScreen");
>     /*\* you can call  {@link PermissionHelper#openSettingsScreen(Context)} to open the settings screen */
> }
> 
> @Override
> public void onNoPermissionNeeded() {
>     // result.setText("Permission(s) not needed");
>     Log.i("onNoPermissionNeeded", "Permission(s) not needed");
> }
> public AlertDialog getAlertDialog(final String[] permissions, final String permissionName) {
>     if (builder == null) {
>         builder = new AlertDialog.Builder(this)
>                 .setTitle("Permission Needs Explanation").create();
>     }
>     builder.setButton(DialogInterface.BUTTON_POSITIVE, "Request", new DialogInterface.OnClickListener() {
>         @Override
>         public void onClick(DialogInterface dialog, int which) {
>             permissionHelper.requestAfterExplanation(permissions);
>         }
>     });
>     builder.setMessage(" Please allow for the smooth function of App");
>     return builder;
> }
> 
> @Override
> protected void onResume() {
>     super.onResume();
> 
> ```
> // register GCM registration complete receiver
> LocalBroadcastManager.getInstance(this).registerReceiver(mRegistrationBroadcastReceiver,
>         new IntentFilter(Config.REGISTRATION_COMPLETE));
> 
> // register new push message receiver
> // by doing this, the activity will be notified each time a new message arrives
> LocalBroadcastManager.getInstance(this).registerReceiver(mRegistrationBroadcastReceiver,
>         new IntentFilter(Config.PUSH_NOTIFICATION));
> ```
> 
> }
> 
> @Override
> protected void onPause() {
>     LocalBroadcastManager.getInstance(this).unregisterReceiver(mRegistrationBroadcastReceiver);
>     super.onPause();
> }
> 
> }
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/k0shk0sh/PermissionHelper/issues/10#issuecomment-203280778

## 

Thanks.
Best Regards, Kosh

**Comment by k0shk0sh** [comment]
Could you please post your manifest permissions here? and again i have tested your code in my local and it works running on 6.0 emulator. for the mean time i dont have 6.0.1 device but i might get my hand on one later like 5 hours from now. could you please provide your manifest ?

**Comment by k0shk0sh** [comment]
and btw, you don't need to call     `permissionHelper.onActivityForResult(requestCode);` as you dont ask for `SYSTEM_ALERT` permission

**Comment by k0shk0sh** [comment]
> Could you please post your manifest permissions here? and again i have
> tested your code in my local and it works running on 6.0 emulator. for the
> mean time i dont have 6.0.1 device but i might get my hand on one later
> like 5 hours from now. could you please provide your manifest ?
> and btw, you don't need to call
> permissionHelper.onActivityForResult(requestCode); as you dont ask for
> SYSTEM_ALERT permission

_Thanks._
_Best Regards,_
_Kosh_

https://about.me/imkosh?promo=email_sig

**Comment by vishnuchd** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="package name">

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<!-- Required for Google Login -->
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.USE_CREDENTIALS" />
<!-- needed for older devices -
    used to check app background / foreground status -->
<uses-permission android:name="android.permission.GET_TASKS" />

<!-- START Added for GCM -->
<uses-permission android:name="android.permission.WAKE_LOCK" />
<permission
    android:name="com.package.permission.C2D_MESSAGE"
    android:protectionLevel="signature" />

<uses-permission android:name="com.package.permission.C2D_MESSAGE" />
<!-- END Added for GCM -->
<application
    android:name=".AppController"
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:supportsRtl="true"
    android:theme="@style/AppTheme">

    <!-- <activity -->
    <!-- android:name="com.facebook.LoginActivity" -->
    <!-- android:theme="@android:style/Theme.Translucent.NoTitleBar" > -->
    <!-- </activity> -->
    <!-- <activity -->
    <!-- android:name="com.facebook.LoginActivity" -->
    <!-- android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" -->
    <!-- android:label="@string/app_name" -->
    <!-- android:theme="@android:style/Theme.Translucent.NoTitleBar" /> -->

    <activity
        android:name=".SplashScreen"
        android:label="@string/app_name"
        android:theme="@style/fullScreen">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
    <activity
        android:name=".Login"
        android:label="@string/title_activity_login"
        android:theme="@style/AppTheme.NoActionBar"
        android:windowSoftInputMode="adjustResize" />
    <activity
        android:name=".Register"
        android:label="@string/title_activity_register"
        android:theme="@style/AppTheme.NoActionBar" />

    <meta-data
        android:name="com.facebook.sdk.ApplicationId"
        android:value="@string/facebook_app_id" />
    <meta-data
        android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />


    </activity>
    <activity
        android:name=".ScrollingActivity"
        android:label="@string/title_activity_scrolling"
          </activity>


    <!-- START Added for GCM -->
    <receiver
        android:name="com.google.android.gms.gcm.GcmReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND">
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />

            <category android:name="com.techprastish.xcollege" />
        </intent-filter>
    </receiver>

    <service
        android:name=".GCM.MyGcmPushReceiver"
        android:exported="false">
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        </intent-filter>
    </service>

    <service
        android:name=".GCM.GcmIntentService"
        android:exported="false">
        <intent-filter>
            <action android:name="com.google.android.gms.iid.InstanceID" />
        </intent-filter>
    </service>

    <!-- END Added for GCM -->


</application>
```

</manifest>

**Comment by vishnuchd** [comment]
@k0shk0sh Thanks for your support. This Library helped me a lot

**Comment by k0shk0sh** [comment]
please do update to latest version **v1.0.10** and let me know.

**Comment by sgaikar1** [comment]
@k0shk0sh This problem still exists in Android 6.0.1.
I am using v1.0.11 but still not getting expected multiple permissions.. it shows only first permission from list. and if first permission is granted then only it displays next one.. but it is not showing non granted permissions in queue.. as shown in images above by @drchopper
