### ISSUE TITLE
Rquest without Callback

### ISSUE THREAD

**Issue by drchopper** [k0shk0sh/PermissionHelper#11]
Hi,

is it possible to set a request without using the OnPermissionCallback.

Like this:

```

boolean isGranted = permissionHelper
     .setForceAccepting(false)// true if you had like force reshowing the permission dialog on Deny (not recommended)
     .request(isSingle ? SINGLE_PERMISSION : MULTIPLE_PERMISSIONS);
```

if user declined (boolean = false) -> ask next time again
if user really declined (boolean = false) - > open a dialog with "open Settings" buttom
if user granted (boolean = true) - > do nothing

do you know what i mean?

cheers

**Comment by k0shk0sh** [comment]
the library will return you callback if the permissions asked are granted and always you can use of the PermissionHelper static or non-static methods to determine if the permission is granted or no. it can even tell you if the permission permanently denied. please have a look at the readme and regards the other issue i haven't yet got my hand on a device running 6.0.1 so i'll keep you updated, however as i mentioned the library works as intended in 6.0 .
