### ISSUE TITLE
Requesting WRITE_SETTINGS permission

### ISSUE THREAD

**Issue by vajiralasantha** [k0shk0sh/PermissionHelper#16]
First of all thank you for this great library. However in my app I need to get WRITE_SETTINGS permission and I use following block of code.

permissions.add(PermissionModelBuilder.withContext(this)
                .withCanSkip(false)
                .withPermissionName(Manifest.permission.WRITE_SETTINGS)
                .withTitle("CHANGE BRIGHTNESS SETTINGS")
                .withMessage("This permission is required for this app to change brightness settings of this device.")
                .withExplanationMessage(R.string.explanation_message_get_settings)
                .withFontType("my_font.ttf")
                .withLayoutColorRes(R.color.colorPrimary)
                .withImageResourceId(R.drawable.permission_three)
                .build());

This does not prompt me to get system settings and it simply skip to next page (using SamplePagerActivity).

I have defined **uses-permission android:name="android.permission.WRITE_SETTINGS"** in Manifest file as well.

Do you have any idea why? Appreciate your help. Thanks.

**Comment by k0shk0sh** [comment]
the user has to allow this permission manually
[Stackoverflow](http://stackoverflow.com/a/35285034/1627904)
