### ISSUE TITLE
Allow button is not working in Nexus 5

### ISSUE THREAD

**Issue by ddpatel2606** [k0shk0sh/PermissionHelper#17]
Hello,

I have checked your code is working perfectly in Nexus 6P

But i have an issue of not press Allow button Properly in Nexus 5 

Please check it.

Thanks,
Dixit Patel

**Comment by athkalia** [comment]
it's not related to the library, it's a nexus 5 android bug 
http://stackoverflow.com/questions/37829165/allow-button-not-working-after-update
