### ISSUE TITLE
Something went wrong with release .10

### ISSUE THREAD

**Issue by mwinters-stuff** [k0shk0sh/PermissionHelper#19]
The uploaded artifacts (source and aar) have the request method in base with the == not the latest >= on the sdk check..

Looks a bit like the wrong artifact got uploaded. the release zip is fine..

**Comment by k0shk0sh** [comment]
o0ops, i'm uploading new version right now  **v.1.0.11**

**Comment by k0shk0sh** [comment]
please update to **v1.0.11**
Thank you for your help.
