### ISSUE TITLE
Multiple permissions

### ISSUE THREAD

**Issue by sgaikar1** [k0shk0sh/PermissionHelper#22]
@k0shk0sh This problem still exists in Android 6.0.1.
I am using v1.0.11 but still not getting expected multiple permissions.. it shows only first permission from list. and if first permission is granted then only it displays next one.. but it is not showing non granted permissions in queue.. as shown in images above by @drchopper
i have tried as said in #10 this issue but dint worked for me

**Comment by k0shk0sh** [comment]
could you please tell if this occur in <6.0.1?

**Comment by sgaikar1** [comment]
yup it is

**Comment by k0shk0sh** [comment]
i guess i kinda know why, will check it later today

**Comment by k0shk0sh** [comment]
well, i found what is the root cause. will fix it by today and push an update. 
silly logic handling.

**Comment by sgaikar1** [comment]
Please let me know when  you will done  with update.. and thanks for your awesome library :)

**Comment by k0shk0sh** [comment]
i did test out the library just now, and it appears to be working fine even tho, im not requesting the permissions all together, but by separating them, still the dialog will appear even after denying the permission, i made the permissions to be asked multiple times at ones, however adding System.Alert permission won't work, you can update to **v 1.0.13**. thank you

**Comment by sgaikar1** [comment]
@k0shk0sh  yeah it works.. thanx man.. you are just awesome...
