### ISSUE TITLE
PermissionModelBuilder in ActivityMain?

### ISSUE THREAD

**Issue by digitalprecision** [k0shk0sh/PermissionHelper#24]
Can you post an example of how to reference an array element from SamplePagerActivity in SampleActivity? I am trying to customize the boxes, but when I call 

`permissionHelper
            .setForceAccepting(false)
            .request(MULTI_PERMISSIONS);`

No customizations appear. Just the default alerts.

**Comment by k0shk0sh** [comment]
SimplePagerActivity extends PermissionHelper base activity which in return it handle that for you. You must extend that activity to accomplish the guide through pagination. Please follow that class and you should be good to go.

**Comment by digitalprecision** [comment]
Does it match automatically based on permission name?

**Comment by k0shk0sh** [comment]
if you actually wants to have it totally customized then you should check the base activity and then see how does it work and use it as you wish, however i suggest that you extend that activity as it handle all the stuff for you. please let me know what use case you trying to achieve without extending the base activity

**Comment by digitalprecision** [comment]
I am trying to do something like this: https://gist.github.com/digitalprecision/dce876fb3a2d0c444e9f883b0d15bf35

**Comment by k0shk0sh** [comment]
well, you shouldn't not use PermissionModelBuilder in this case as its redundant, it does not but construct a model class that is used by the BasePermissionAcitivity, if you like to request permissions by yourself then you should follow the SampleActivity without caring about Pagination, if you do case about having like some sort of education kind of UI and requesting an individual permissions separately then you should follow SimplePagerActivity

**Comment by k0shk0sh** [comment]
well, im kinda sorry if my comment does not make sense as im using phone to reply you.

**Comment by digitalprecision** [comment]
Np, I appreciate you responding. It sort of makes sense. If I got the SampleActivity route, how would I add the explanation? The alert dialog code in the SampleActivity file only passes in the permission, no explanation message. Should I just do a switch case on permission string?

**Comment by k0shk0sh** [comment]
In this case permissions explanation are required when only the permission
is being declined and then you asked for the permission again, in thise you
should show the explanation, if you had like to show an explanation before
promoting for accepting the permission, maybe you better go with an
AlerDialog with an explanation message and upon clicking on a button within
the dialog, you actually ask permissionHelper to request the permission for
you.

**Comment by digitalprecision** [comment]
Gotcha. Ok, thanks. Working on implementing the pager to add styling.

**Comment by k0shk0sh** [comment]
good luck, anything please do ask back here and if im available i will try my best to help. meantime i will be closing this issue.

**Comment by digitalprecision** [comment]
Awesome, thanks! Appreciate the api.

**Comment by digitalprecision** [comment]
How do I prompt user to grant a permission stored in the permissions array as built following the SamplePagerActivity file?

I tried `permissions().get(0);` but nothing happens.
