### ISSUE TITLE
Camera access example

### ISSUE THREAD

**Issue by digitalprecision** [k0shk0sh/PermissionHelper#25]
Seems easy enough:

```
protected void intentCamera()
{
    permissionHelper
        .setForceAccepting(false)
        .request(MULTI_PERMISSIONS); // CAMERA and WRITE_EXTERNAL_STORAGE

    showCamera();
}
```

But doesn't work as expected, as `showCamera()` is called regardless of the status of the permissions. Does `showCamera()` go into `onRequestPermissionsResult()`?

**Comment by k0shk0sh** [comment]
It goes into the on permission granted callback, when the permission is granted you should start the camera. in ur above code, the method will always be called.

**Comment by digitalprecision** [comment]
But that method handles a specific permission. For camera I need Camera and Write_External. How would I call cameraStart if one perm is camera but the next is Write_External? I need both to be granted then call cameraStart.

**Comment by k0shk0sh** [comment]
You should be using one of permissionHelper methods to tell you if both
permissions are granted on permission granted callback  ex: if
permissionHelper.isPermissionGranted(....) and
permissionHelper.isPermissionGranted(....) Do things.

**Comment by digitalprecision** [comment]
Ya I tried that first. But if u wrap startCamera with those perms it won't fire off if the perms were just granted. I have to click the button again then the camera opens.

**Comment by k0shk0sh** [comment]
@Override public void onPermissionGranted(@NonNull String[] permissionName)
{ //do the checking here. This method will always be called if permissions
is granted. Its straight forward tbh }

**Comment by digitalprecision** [comment]
For a single permission right? I can't call startCamera in that method for the reason I stated above. I need both perms to be granted.

**Comment by k0shk0sh** [comment]
if you called request with multiple permissions, then that method method will return multiple permissions if they are granted. 

`public static List<String> declinedPermissionsAsList(@NonNull Context context, @NonNull String[] permissions) {`

you might consider using that method `onPermissionGranted` this method will return you declined permissions, if its empty then both permissions are granted.

**Comment by digitalprecision** [comment]
Dope I'll try that. Thanks.
