### ISSUE TITLE
When the permission(s) granted, can't know which action request the permission(s).

### ISSUE THREAD

**Issue by 1vvvf** [k0shk0sh/PermissionHelper#31]
**For Example:**
In an Activity, there are two actions(download, take photos) that request _Manifest.permission.WRITE_EXTERNAL_STORAGE_.

Before start download action, request the permission, and then the permission is granted.
Now, What to do next? (Notice that taking photos also require and request the permission.)

**The next step is to download or to take photos?**

**Comment by k0shk0sh** [comment]
Hello Erehmi, I can't really tell you how your app should behave especially I'v no clue how your app should function, but what i can advice is, request the permission you like to request before an action is taken that requires the specific permission.
