### ISSUE TITLE
No onPermissionNeedExplanation when requested with multiple permission

### ISSUE THREAD

**Issue by aaabidunique** [k0shk0sh/PermissionHelper#33]
When I try to request multiple permission and user has already denied them once, it is supposed to call onPermissionNeedExplanation but it doesn't do that but this works fine it I call one permission at a time.
Please fix this issue.

Edit:
Even if I request each permission one by one it shows onPermissionNeedExplanation for only first one and for others it requests permission i.e onPermissionNeedExplanation and permission dialog gets overlapped.

**Comment by k0shk0sh** [comment]
Could you show an example code that demonstrate the issue? Also can u try the sample app and see if you can produce it with it?

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
