### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by paulocoutinhox** [k0shk0sh/PermissionHelper#35]
This project is abandoned?

I can use it in my project without problems?

**Comment by k0shk0sh** [comment]
@prsolucoes Hi there, it's consider stable so nothing much to do here unless if you find a bug or you have Feature request. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
