### ISSUE TITLE
Notification Access Permissions

### ISSUE THREAD

**Issue by rammadogs** [k0shk0sh/PermissionHelper#37]
Hey, it would be awesome if you could implement support for android.provider.Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS. This is similar to the system alert window permission in that you need to go to settings to change it.

**Comment by rammadogs** [comment]
I've created a fork which implements the functionality :) https://github.com/rammadogs/PermissionHelper

**Comment by k0shk0sh** [comment]
Then open a pr with it
