### ISSUE TITLE
[Feature request] Create slide without permission

### ISSUE THREAD

**Issue by DevilGeek** [k0shk0sh/PermissionHelper#6]
The slider thing is great but it would be cooll if we can add a slide that does not ask for permission.

atm if i build a slide without calling withPermissionName it crash
 java.lang.IllegalArgumentException: Unknown permission: null

**Comment by k0shk0sh** [comment]
Hello DevilGeek, thanks for using PermissionHelper, the library is meant to be used for Permissions and not an intro. only it'll become Intro when you target apis <23. if you like the intro, you could however clone the library and modified it the way you like. 
Thanks
